# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_data',
            name='enquiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
