# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170127_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
