# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 30, 18, 21, 14, 427000, tzinfo=utc)),
        ),
    ]
