# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center1', models.DecimalField(decimal_places=7, max_digits=15, max_length=10)),
                ('center2', models.DecimalField(decimal_places=7, max_digits=15, max_length=10)),
                ('name', models.CharField(max_length=50, null=True)),
                ('zoom', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
            ],
        ),
    ]
