# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdetails',
            name='center1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mapdetails',
            name='center2',
            field=models.CharField(max_length=10),
        ),
    ]
