# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20170210_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdetails',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
