# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('quantity_availabe', models.IntegerField(default=0)),
            ],
        ),
    ]
